[project]
name = "deep-peep-snooker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "lightning",
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.92",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "scikit-learn>=1.8.0",
    "shapely>=2.1.2",
    "torch",
    "torchvision",
]

[tool.uv]
[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.6",
    "odfpy>=1.4.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "tyro>=1.0.8",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.sources]
"src" = ""